config/routes.rb
Backbone::Application.routes.draw do
  resources :documents

  root :to => "documents#home"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :body, :title

  def to_json(options = {})
    super(options.merge(:only => [ :id, :title, :created_at, :body ]))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def home
    respond_to do |format|
      format.html # home.html.erb
    end
  end

  def index
    render :json => Document.all
  end

  def show
    render :json => Document.find(params[:id])
  end

  def create
    document = Document.create! params
    render :json => document
  end

  def update
    document = Document.find(params[:id])
    document.update_attributes! params
    render :json => document
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/home.html.erb
<h1><a href="#">CloudEdit</a></h1>
<h2>A Backbone.js Rails Example</h2>
<div id="notice"></div>
<div id="app"></div>
<script type="text/javascript">
    $(function() {
        App.init();
    });
</script>

app/views/documents/index.html.erb
<h1><a href="#">Home</a></h1>
<div id="notice"></div>
<div id="app"></div>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backbone</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.6.2', 'json2', 'jquery.ba-dotimeout.min','underscore', 'backbone', 'application', 'models/document', 'collections/documents', 'controllers/documents', 'views/edit', 'views/index', 'views/notice' %>
  <%= include_stylesheets :common, :workspace, :media => 'all' %>
  <%= include_javascripts :workspace %>
  <%= csrf_meta_tag %>
</head>
<body>
<%= yield %>
</body>
</html>